### ISSUE TITLE
Add support for Henshin 1.4 / 1.5 (1.6) -- align with Henshin release plans

### ISSUE THREAD

**Issue by szschaler** [szschaler/henshin_xdsmls#15]
Creating a proper issue to track this. Sorry, @dstrueber, could you provide any intel on the Henshin team plans here rather than in issue #11?

**Comment by dstrueber** [comment]
Hi Steffen! We plan to have a release ready by summer. This would be version 1.6 (note that releases have even version numbers, as opposed to the nightly-build versions).

**Comment by szschaler** [comment]
Thanks. What's the most efficient way for us to stay on top of developments?

**Comment by dstrueber** [comment]
If your requirement is to depend on stable releases only, and you want to release before summer, you might need to backport. Otherwise, you can wait for our release.

**Comment by szschaler** [comment]
Appreciated. I meant, is there some channel we should watch to learn about the new release as soon as it comes out?

**Comment by dstrueber** [comment]
We will announce it on the two mailing lists (henshin-dev, henshin-user).

**Comment by szschaler** [comment]
Done in PR #30
